const questions=[
{category:"Science",art:"🪐",question:"Which planet is known as the Red Planet?",answers:["Venus","Mars","Jupiter","Saturn"],correct:1,explanation:"Mars appears red because iron minerals on its surface oxidize and create a rust-like color."},
{category:"Geography",art:"🌍",question:"What is the capital city of Australia?",answers:["Sydney","Melbourne","Canberra","Perth"],correct:2,explanation:"Canberra was chosen as the capital as a compromise between Sydney and Melbourne."},
{category:"Animals",art:"🐋",question:"Which animal is the largest mammal on Earth?",answers:["African elephant","Blue whale","Giraffe","Whale shark"],correct:1,explanation:"The blue whale is the largest known animal to have lived on Earth."},
{category:"Technology",art:"💻",question:"What does CPU stand for?",answers:["Central Processing Unit","Computer Personal Utility","Core Program User","Central Power Utility"],correct:0,explanation:"CPU means Central Processing Unit, the processor that executes instructions."},
{category:"History",art:"🏛️",question:"Which ancient civilization built Machu Picchu?",answers:["Romans","Maya","Inca","Egyptians"],correct:2,explanation:"Machu Picchu was built by the Inca civilization during the 15th century."},
{category:"Sport",art:"⚽",question:"How many players does one football team have on the field?",answers:["9","10","11","12"],correct:2,explanation:"A football team normally has 11 players on the field, including the goalkeeper."}
];
const letters=["A","B","C","D"];let current=0,timeLeft=10,timerId,answered=false;
const categoryLabel=document.getElementById("categoryLabel"),questionCounter=document.getElementById("questionCounter"),questionText=document.getElementById("questionText"),questionArt=document.getElementById("questionArt"),answerGrid=document.getElementById("answerGrid"),feedbackTitle=document.getElementById("feedbackTitle"),explanationText=document.getElementById("explanationText"),nextButton=document.getElementById("nextButton"),timer=document.getElementById("timer"),timerFill=document.getElementById("timerFill");
function render(){clearInterval(timerId);answered=false;timeLeft=10;const q=questions[current];categoryLabel.textContent=q.category;questionCounter.textContent=`Question ${current+1} of ${questions.length}`;questionText.textContent=q.question;questionArt.textContent=q.art;feedbackTitle.textContent="Choose one answer.";explanationText.textContent="The answer and explanation will appear here.";nextButton.disabled=true;answerGrid.innerHTML="";q.answers.forEach((answer,i)=>{const b=document.createElement("button");b.className="answer-button";b.type="button";b.innerHTML=`<span class="answer-letter">${letters[i]}</span><span>${answer}</span>`;b.addEventListener("click",()=>choose(i));answerGrid.appendChild(b)});updateTimer();timerId=setInterval(()=>{timeLeft--;updateTimer();if(timeLeft<=0){clearInterval(timerId);reveal(null)}},1000)}
function updateTimer(){timer.textContent=timeLeft;timerFill.style.width=`${timeLeft*10}%`}
function choose(i){if(answered)return;clearInterval(timerId);reveal(i)}
function reveal(selected){answered=true;const q=questions[current];[...document.querySelectorAll(".answer-button")].forEach((b,i)=>{b.disabled=true;if(i===q.correct)b.classList.add("correct");if(i===selected&&i!==q.correct)b.classList.add("wrong")});feedbackTitle.textContent=selected===null?`Time is up. The answer is ${letters[q.correct]}: ${q.answers[q.correct]}.`:selected===q.correct?"Correct. Well done!":`The correct answer is ${letters[q.correct]}: ${q.answers[q.correct]}.`;explanationText.textContent=q.explanation;nextButton.disabled=false}
nextButton.addEventListener("click",()=>{current=(current+1)%questions.length;render()});render();